// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Analytics provides access to the analytics toolkit.
type Analytics struct {
  client *Client
}

// NewAnalytics creates a new Analytics client.
func NewAnalytics(apiKey string, opts ...Option) *Analytics {
  return &Analytics{client: NewClient(apiKey, "analytics", opts...)}
}

// Analyze Analyze a remote dataset with natural language
func (s *Analytics) Analyze(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/analyze", body, nil)
}

// Save Save analysis logic for replay
func (s *Analytics) Save(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/save", body, nil)
}

// Run Re-execute saved analysis logic
func (s *Analytics) Run(ctx context.Context, queryId string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, fmt.Sprintf("v1/query/%s", queryId), body, nil)
}

// Visualize Generate a chart from a dataset
func (s *Analytics) Visualize(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/visualize", body, nil)
}

// Download Download a generated chart image
func (s *Analytics) Download(ctx context.Context, imageId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/image/download/%s", imageId), nil)
}

// Validate Validate a chart spec without executing
func (s *Analytics) Validate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/validate-chart", body, nil)
}

// Get Retrieve dataset schema
func (s *Analytics) Get(ctx context.Context, datasetId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/datasets/%s/schema", datasetId), nil)
}

// Create Register a multi-source bundle for joins
func (s *Analytics) Create(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/datasets/bundle", body, nil)
}

// Status Service health check
func (s *Analytics) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
