// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Auth provides access to the auth toolkit.
type Auth struct {
  client *Client
}

// NewAuth creates a new Auth client.
func NewAuth(apiKey string, opts ...Option) *Auth {
  return &Auth{client: NewClient(apiKey, "auth", opts...)}
}

// HashPassword Hash a password
func (s *Auth) HashPassword(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/hash-password", body, nil)
}

// Verify Verify a password against a hash
func (s *Auth) Verify(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/verify-password", body, nil)
}

// Password Analyze password strength
func (s *Auth) Password(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/password-strength", body, nil)
}

// GeneratePassword Generate secure random passwords
func (s *Auth) GeneratePassword(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/generate-password", body, nil)
}

// JWTGenerate Generate a JWT token
func (s *Auth) JWTGenerate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/jwt-generate", body, nil)
}

// JWTVerify Verify a JWT token
func (s *Auth) JWTVerify(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/jwt-verify", body, nil)
}

// JWTDecode Decode a JWT without verification
func (s *Auth) JWTDecode(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/jwt-decode", body, nil)
}

// TOTPGenerate Generate a TOTP secret and QR code
func (s *Auth) TOTPGenerate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/auth/totp-generate", params)
}

// TOTPVerify Verify a TOTP code
func (s *Auth) TOTPVerify(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/totp-verify", body, nil)
}

// GenerateKey Generate a random key or identifier
func (s *Auth) GenerateKey(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/auth/generate-key", params)
}

// GenerateKeypair Generate an asymmetric keypair
func (s *Auth) GenerateKeypair(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/generate-keypair", body, nil)
}

// Encrypt Encrypt plaintext with AES-256-GCM
func (s *Auth) Encrypt(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/encrypt", body, nil)
}

// Decrypt Decrypt ciphertext with AES-256-GCM
func (s *Auth) Decrypt(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/decrypt", body, nil)
}

// Hash2 Hash a string
func (s *Auth) Hash2(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/hash", body, nil)
}

// Hmac2 Generate an HMAC
func (s *Auth) Hmac2(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/hmac", body, nil)
}

// HmacVerify Verify an HMAC signature
func (s *Auth) HmacVerify(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/hmac-verify", body, nil)
}

// Base64Encode Base64 encode a string
func (s *Auth) Base64Encode(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/base64-encode", body, nil)
}

// Base64Decode Base64 decode a string
func (s *Auth) Base64Decode(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/base64-decode", body, nil)
}

// Encode Encode or decode a string
func (s *Auth) Encode(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/auth/encode", body, nil)
}

// Root Root
func (s *Auth) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Auth) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
