// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Barcode provides access to the barcode toolkit.
type Barcode struct {
  client *Client
}

// NewBarcode creates a new Barcode client.
func NewBarcode(apiKey string, opts ...Option) *Barcode {
  return &Barcode{client: NewClient(apiKey, "barcode", opts...)}
}

// QrGenerate Generate a styled QR code
func (s *Barcode) QrGenerate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/qr/generate", body, nil)
}

// QrGenerate1 Generate a QR code (raw image)
func (s *Barcode) QrGenerate1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/qr/generate", params)
}

// QrDecode Decode QR code(s) from an image
func (s *Barcode) QrDecode(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/qr/decode", body, nil)
}

// QrBulk Bulk-generate QR codes
func (s *Barcode) QrBulk(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/qr/bulk", body, nil)
}

// BarcodeGenerateGenerate Generate a barcode
func (s *Barcode) BarcodeGenerateGenerate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/barcode/generate", body, nil)
}

// BarcodeGenerateGenerate1 Generate a barcode (raw image)
func (s *Barcode) BarcodeGenerateGenerate1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/barcode/generate", params)
}

// BarcodeDecode Decode barcode(s) from an image
func (s *Barcode) BarcodeDecode(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/barcode/decode", body, nil)
}

// BarcodeBulk Bulk-generate barcodes
func (s *Barcode) BarcodeBulk(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/barcode/bulk", body, nil)
}

// BarcodeTypes List supported barcode types
func (s *Barcode) BarcodeTypes(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/barcode/types", nil)
}

// Root Root
func (s *Barcode) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Barcode) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
