// Code generated by generate_go_sdk.js. DO NOT EDIT.
package toolkitapi

import (
  "bytes"
  "context"
  "encoding/json"
  "fmt"
  "io"
  "net/http"
  "net/url"
  "time"
)

// Client is the HTTP client for ToolkitAPI.
type Client struct {
  httpClient *http.Client
  baseURL    string
  apiKey     string
}

// Option configures the Client.
type Option func(*Client)

// WithBaseURL overrides the default base URL.
func WithBaseURL(url string) Option {
  return func(c *Client) { c.baseURL = url }
}

// WithTimeout sets the HTTP client timeout.
func WithTimeout(d time.Duration) Option {
  return func(c *Client) {
    c.httpClient.Timeout = d
  }
}

// NewClient creates a new ToolkitAPI client.
func NewClient(apiKey, toolkit string, opts ...Option) *Client {
  c := &Client{
    httpClient: &http.Client{Timeout: 30 * time.Second},
    baseURL:    fmt.Sprintf("https://%s.toolkitapi.io", toolkit),
    apiKey:     apiKey,
  }
  for _, opt := range opts {
    opt(c)
  }
  return c
}

// doRequest sends an HTTP request and returns the parsed JSON body.
func (c *Client) doRequest(ctx context.Context, method, path string, body io.Reader, contentType string) (interface{}, error) {
  req, err := http.NewRequestWithContext(ctx, method, c.baseURL+"/"+path, body)
  if err != nil {
    return nil, fmt.Errorf("creating request: %w", err)
  }
  req.Header.Set("X-API-Key", c.apiKey)
  req.Header.Set("Accept", "application/json")
  if contentType != "" {
    req.Header.Set("Content-Type", contentType)
  }

  resp, err := c.httpClient.Do(req)
  if err != nil {
    return nil, fmt.Errorf("sending request: %w", err)
  }
  defer resp.Body.Close()

  if resp.StatusCode < 200 || resp.StatusCode >= 300 {
    bodyBytes, _ := io.ReadAll(resp.Body)
    return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(bodyBytes))
  }

  var result interface{}
  if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
    return nil, fmt.Errorf("decoding response: %w", err)
  }
  return result, nil
}

func (c *Client) Get(ctx context.Context, path string, params map[string]string) (interface{}, error) {
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodGet, path, nil, "")
}

func (c *Client) Post(ctx context.Context, path string, body interface{}, params map[string]string) (interface{}, error) {
  var bodyReader io.Reader
  if body != nil {
    jsonBody, err := json.Marshal(body)
    if err != nil {
      return nil, fmt.Errorf("encoding body: %w", err)
    }
    bodyReader = bytes.NewReader(jsonBody)
  }
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodPost, path, bodyReader, "application/json")
}

func (c *Client) Put(ctx context.Context, path string, body interface{}, params map[string]string) (interface{}, error) {
  var bodyReader io.Reader
  if body != nil {
    jsonBody, err := json.Marshal(body)
    if err != nil {
      return nil, fmt.Errorf("encoding body: %w", err)
    }
    bodyReader = bytes.NewReader(jsonBody)
  }
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodPut, path, bodyReader, "application/json")
}

func (c *Client) Delete(ctx context.Context, path string, params map[string]string) (interface{}, error) {
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodDelete, path, nil, "")
}

func (c *Client) Patch(ctx context.Context, path string, body interface{}, params map[string]string) (interface{}, error) {
  var bodyReader io.Reader
  if body != nil {
    jsonBody, err := json.Marshal(body)
    if err != nil {
      return nil, fmt.Errorf("encoding body: %w", err)
    }
    bodyReader = bytes.NewReader(jsonBody)
  }
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodPatch, path, bodyReader, "application/json")
}

func (c *Client) Options(ctx context.Context, path string, body interface{}, params map[string]string) (interface{}, error) {
  var bodyReader io.Reader
  if body != nil {
    jsonBody, err := json.Marshal(body)
    if err != nil {
      return nil, fmt.Errorf("encoding body: %w", err)
    }
    bodyReader = bytes.NewReader(jsonBody)
  }
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodOptions, path, bodyReader, "application/json")
}

func (c *Client) Head(ctx context.Context, path string, body interface{}, params map[string]string) (interface{}, error) {
  if params != nil && len(params) > 0 {
    path += "?" + encodeParams(params)
  }
  return c.doRequest(ctx, http.MethodHead, path, nil, "")
}

func encodeParams(params map[string]string) string {
  vals := url.Values{}
  for k, v := range params {
    vals.Set(k, v)
  }
  return vals.Encode()
}
