// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Convert provides access to the convert toolkit.
type Convert struct {
  client *Client
}

// NewConvert creates a new Convert client.
func NewConvert(apiKey string, opts ...Option) *Convert {
  return &Convert{client: NewClient(apiKey, "convert", opts...)}
}

// ConvertDataData Convert between data formats
func (s *Convert) ConvertDataData(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/data", body, nil)
}

// ConvertDataData1 Convert data format via URL (file download)
func (s *Convert) ConvertDataData1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/data", params)
}

// ConvertMarkupMarkup Convert between markup formats
func (s *Convert) ConvertMarkupMarkup(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/markup", body, nil)
}

// ConvertMarkupMarkup1 Convert markup format via URL (file download)
func (s *Convert) ConvertMarkupMarkup1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/markup", params)
}

// JSON Generate TypeScript interfaces from JSON
func (s *Convert) JSON(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/json-to-typescript", body, nil)
}

// ConvertDocumentDocument Convert between document formats
func (s *Convert) ConvertDocumentDocument(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/document", body, nil)
}

// ConvertDocumentDocument1 Convert document via URL (file download)
func (s *Convert) ConvertDocumentDocument1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/document", params)
}

// ConvertSpreadsheetSpreadsheet Convert between spreadsheet formats
func (s *Convert) ConvertSpreadsheetSpreadsheet(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/spreadsheet", body, nil)
}

// ConvertSpreadsheetSpreadsheet1 Convert spreadsheet via URL (file download)
func (s *Convert) ConvertSpreadsheetSpreadsheet1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/spreadsheet", params)
}

// ConvertCalendar Convert between calendar and contact formats
func (s *Convert) ConvertCalendar(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/calendar", body, nil)
}

// ConvertPresentationPresentation Convert presentation to PDF
func (s *Convert) ConvertPresentationPresentation(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/presentation", body, nil)
}

// ConvertPresentationPresentation1 Convert presentation via URL (file download)
func (s *Convert) ConvertPresentationPresentation1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/presentation", params)
}

// ConvertEbookEbook Convert ebook formats
func (s *Convert) ConvertEbookEbook(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/ebook", body, nil)
}

// ConvertEbookEbook1 Convert ebook via URL (file download)
func (s *Convert) ConvertEbookEbook1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/ebook", params)
}

// ListFormats List all supported conversion formats
func (s *Convert) ListFormats(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/formats", nil)
}

// ListFormats1 List conversion formats for a category
func (s *Convert) ListFormats1(ctx context.Context, category string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/convert/formats/%s", category), nil)
}

// Poll Poll async conversion job status
func (s *Convert) Poll(ctx context.Context, jobId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("convert/jobs/%s", jobId), nil)
}

// Supported List supported media conversion formats
func (s *Convert) Supported(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/supported-media-formats", nil)
}

// ConvertMediaMedia Convert a media file (video or audio)
func (s *Convert) ConvertMediaMedia(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/media", body, nil)
}

// ConvertMediaMedia1 Convert media via URL query params (streaming download)
func (s *Convert) ConvertMediaMedia1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/media", params)
}

// Video Extract a thumbnail frame from a video
func (s *Convert) Video(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/video-thumbnail", body, nil)
}

// Media Probe media file for metadata
func (s *Convert) Media(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/media-info", body, nil)
}

// Download Download a converted file
func (s *Convert) Download(ctx context.Context, objectName string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/convert/download/%s", objectName), nil)
}

// Root Root
func (s *Convert) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Convert) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
