// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Dev provides access to the dev toolkit.
type Dev struct {
  client *Client
}

// NewDev creates a new Dev client.
func NewDev(apiKey string, opts ...Option) *Dev {
  return &Dev{client: NewClient(apiKey, "dev", opts...)}
}

// JSONValidate Json Validate
func (s *Dev) JSONValidate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-validate", body, nil)
}

// JSONDiff Json Diff
func (s *Dev) JSONDiff(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-diff", body, nil)
}

// Yaml Yaml Validate
func (s *Dev) Yaml(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/yaml-validate", body, nil)
}

// Xml Xml Validate
func (s *Dev) Xml(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/xml-validate", body, nil)
}

// Toml Toml Validate
func (s *Dev) Toml(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/toml-validate", body, nil)
}

// JSONSchemaValidate Json Schema Validate
func (s *Dev) JSONSchemaValidate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-schema-validate", body, nil)
}

// Jsonpath Jsonpath Query
func (s *Dev) Jsonpath(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/jsonpath", body, nil)
}

// JSONToSchema Json To Schema
func (s *Dev) JSONToSchema(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-to-schema", body, nil)
}

// Csv Lint and validate CSV data
func (s *Dev) Csv(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/csv-lint", body, nil)
}

// Generate Generate Uuid
func (s *Dev) Generate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/uuid", params)
}

// Password Password Gen
func (s *Dev) Password(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/password-gen", params)
}

// Lorem Lorem Ipsum
func (s *Dev) Lorem(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/lorem-ipsum", params)
}

// Fake Fake Data
func (s *Dev) Fake(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/fake-data", params)
}

// RegexTest Regex Test
func (s *Dev) RegexTest(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/regex-test", body, nil)
}

// RegexExtract Regex Extract
func (s *Dev) RegexExtract(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/regex-extract", body, nil)
}

// RegexParse Regex Parse
func (s *Dev) RegexParse(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/regex-parse", body, nil)
}

// CronParse Cron Parse
func (s *Dev) CronParse(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/cron-parse", params)
}

// CronNext Cron Next
func (s *Dev) CronNext(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/cron-next", params)
}

// Timestamp Timestamp
func (s *Dev) Timestamp(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/timestamp", params)
}

// User User Agent
func (s *Dev) User(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/user-agent", body, nil)
}

// Color Color Convert
func (s *Dev) Color(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/color-convert", params)
}

// Base Base Convert
func (s *Dev) Base(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/base-convert", params)
}

// Semver Semver Compare
func (s *Dev) Semver(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/semver-compare", body, nil)
}

// Chmod Chmod Calc
func (s *Dev) Chmod(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/chmod-calc", params)
}

// Env Env Parse
func (s *Dev) Env(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/env-parse", body, nil)
}

// Diff Diff Text
func (s *Dev) Diff(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/diff", body, nil)
}

// Slugify Slugify
func (s *Dev) Slugify(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/slug", body, nil)
}

// Word Word Count
func (s *Dev) Word(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/word-count", body, nil)
}

// Sql Sql Format
func (s *Dev) Sql(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/sql-format", body, nil)
}

// TextEscape Text Escape
func (s *Dev) TextEscape(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text-escape", body, nil)
}

// TextTruncate Text Truncate
func (s *Dev) TextTruncate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text-truncate", body, nil)
}

// Code Code Format
func (s *Dev) Code(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/code-format", body, nil)
}

// Liquid Liquid Render
func (s *Dev) Liquid(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/liquid-render", body, nil)
}

// JSONTransform Json Transform
func (s *Dev) JSONTransform(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-transform", body, nil)
}

// Math Math Eval
func (s *Dev) Math(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/math-eval", body, nil)
}

// Date Date Format
func (s *Dev) Date(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/date-format", body, nil)
}

// JSONFlatten Json Flatten
func (s *Dev) JSONFlatten(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-flatten", body, nil)
}

// Array Array Ops
func (s *Dev) Array(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/array-ops", body, nil)
}

// Number Number Format
func (s *Dev) Number(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/number-format", body, nil)
}

// MockData Mock Data
func (s *Dev) MockData(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/mock-data", body, nil)
}

// MockSchema Mock Schema
func (s *Dev) MockSchema(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/mock-schema", body, nil)
}

// ConvertData Convert data format (JSON/CSV/XML/YAML/TOML)
func (s *Dev) ConvertData(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/data", params)
}

// ConvertMarkup Convert markup format (Markdown / HTML / text)
func (s *Dev) ConvertMarkup(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/convert/markup", params)
}

// JSONToTypescript Generate TypeScript interfaces from JSON
func (s *Dev) JSONToTypescript(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/convert/json-to-typescript", body, nil)
}

// Vcard Parse vCard (.vcf) to JSON
func (s *Dev) Vcard(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/parse/vcard", body, nil)
}

// JSONGenerate Generate vCard (.vcf) from JSON contacts
func (s *Dev) JSONGenerate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/parse/vcard/generate", body, nil)
}

// Ics Parse ICS calendar to JSON
func (s *Dev) Ics(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/parse/ics", body, nil)
}

// JSONGenerate1 Generate ICS calendar from JSON events
func (s *Dev) JSONGenerate1(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/parse/ics/generate", body, nil)
}

// Root Root
func (s *Dev) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Dev) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
