// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Devtools provides access to the devtools toolkit.
type Devtools struct {
  client *Client
}

// NewDevtools creates a new Devtools client.
func NewDevtools(apiKey string, opts ...Option) *Devtools {
  return &Devtools{client: NewClient(apiKey, "devtools", opts...)}
}

// JSONValidate Json Validate
func (s *Devtools) JSONValidate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-validate", body, nil)
}

// JSONDiff Json Diff
func (s *Devtools) JSONDiff(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-diff", body, nil)
}

// Yaml Yaml Validate
func (s *Devtools) Yaml(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/yaml-validate", body, nil)
}

// Xml Xml Validate
func (s *Devtools) Xml(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/xml-validate", body, nil)
}

// Toml Toml Validate
func (s *Devtools) Toml(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/toml-validate", body, nil)
}

// JSONSchemaValidate Json Schema Validate
func (s *Devtools) JSONSchemaValidate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-schema-validate", body, nil)
}

// Jsonpath Jsonpath Query
func (s *Devtools) Jsonpath(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/jsonpath", body, nil)
}

// JSONToSchema Json To Schema
func (s *Devtools) JSONToSchema(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-to-schema", body, nil)
}

// Csv Lint and validate CSV data
func (s *Devtools) Csv(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/csv-lint", body, nil)
}

// Generate Generate Uuid
func (s *Devtools) Generate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/uuid", params)
}

// Password Password Gen
func (s *Devtools) Password(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/password-gen", params)
}

// Lorem Lorem Ipsum
func (s *Devtools) Lorem(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/lorem-ipsum", params)
}

// Fake Fake Data
func (s *Devtools) Fake(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/fake-data", params)
}

// RegexTest Regex Test
func (s *Devtools) RegexTest(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/regex-test", body, nil)
}

// RegexExtract Regex Extract
func (s *Devtools) RegexExtract(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/regex-extract", body, nil)
}

// RegexParse Regex Parse
func (s *Devtools) RegexParse(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/regex-parse", body, nil)
}

// CronParse Cron Parse
func (s *Devtools) CronParse(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/cron-parse", params)
}

// CronNext Cron Next
func (s *Devtools) CronNext(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/cron-next", params)
}

// Timestamp Timestamp
func (s *Devtools) Timestamp(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/timestamp", params)
}

// User User Agent
func (s *Devtools) User(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/user-agent", body, nil)
}

// Color Color Convert
func (s *Devtools) Color(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/color-convert", params)
}

// Base Base Convert
func (s *Devtools) Base(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/base-convert", params)
}

// Semver Semver Compare
func (s *Devtools) Semver(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/semver-compare", body, nil)
}

// Chmod Chmod Calc
func (s *Devtools) Chmod(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/chmod-calc", params)
}

// Env Env Parse
func (s *Devtools) Env(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/env-parse", body, nil)
}

// Diff Diff Text
func (s *Devtools) Diff(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/diff", body, nil)
}

// Slugify Slugify
func (s *Devtools) Slugify(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/slug", body, nil)
}

// Word Word Count
func (s *Devtools) Word(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/word-count", body, nil)
}

// Sql Sql Format
func (s *Devtools) Sql(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/sql-format", body, nil)
}

// TextEscape Text Escape
func (s *Devtools) TextEscape(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text-escape", body, nil)
}

// TextTruncate Text Truncate
func (s *Devtools) TextTruncate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text-truncate", body, nil)
}

// Code Code Format
func (s *Devtools) Code(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/code-format", body, nil)
}

// Liquid Liquid Render
func (s *Devtools) Liquid(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/liquid-render", body, nil)
}

// JSONTransform Json Transform
func (s *Devtools) JSONTransform(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-transform", body, nil)
}

// Math Math Eval
func (s *Devtools) Math(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/math-eval", body, nil)
}

// Date Date Format
func (s *Devtools) Date(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/date-format", body, nil)
}

// JSONFlatten Json Flatten
func (s *Devtools) JSONFlatten(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/json-flatten", body, nil)
}

// Array Array Ops
func (s *Devtools) Array(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/array-ops", body, nil)
}

// Number Number Format
func (s *Devtools) Number(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/number-format", body, nil)
}

// MockData Mock Data
func (s *Devtools) MockData(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/mock-data", body, nil)
}

// MockSchema Mock Schema
func (s *Devtools) MockSchema(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/mock-schema", body, nil)
}

// Root Root
func (s *Devtools) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Devtools) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
