// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// DNS provides access to the dns toolkit.
type DNS struct {
  client *Client
}

// NewDNS creates a new DNS client.
func NewDNS(apiKey string, opts ...Option) *DNS {
  return &DNS{client: NewClient(apiKey, "dns", opts...)}
}

// Propagation Check DNS propagation across global resolvers
func (s *DNS) Propagation(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/propagation", params)
}

// Lookup Look up DNS records for a domain
func (s *DNS) Lookup(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/lookup", params)
}

// LookupAll Look up all DNS record types for a domain
func (s *DNS) LookupAll(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/lookup/all", params)
}

// LookupBulk Bulk DNS lookup for multiple domains
func (s *DNS) LookupBulk(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/lookup/bulk", body, params)
}

// CompareResolvers Compare DNS responses across major public resolvers
func (s *DNS) CompareResolvers(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/compare-resolvers", params)
}

// DohTest Test DNS-over-HTTPS and DNS-over-TLS providers
func (s *DNS) DohTest(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/doh-test", params)
}

// Idn Convert between IDN (Unicode) and Punycode
func (s *DNS) Idn(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/idn", params)
}

// Whois WHOIS / RDAP lookup for a domain
func (s *DNS) Whois(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/whois", params)
}

// DomainAge Check domain registration age
func (s *DNS) DomainAge(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/domain-age", params)
}

// Available Check if a domain is available for registration
func (s *DNS) Available(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/available", params)
}

// Subdomains Discover subdomains via DNS brute-force
func (s *DNS) Subdomains(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/subdomains", params)
}

// Associated Find associated infrastructure for a domain
func (s *DNS) Associated(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/associated", params)
}

// Disposable Check if a domain is a disposable/temporary email provider
func (s *DNS) Disposable(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/disposable", params)
}

// TldSearch Search keyword availability across 150+ TLDs
func (s *DNS) TldSearch(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/tld-search", params)
}

// AvailableBulk Bulk domain availability check
func (s *DNS) AvailableBulk(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/available/bulk", body, params)
}

// WhoisBulk Bulk WHOIS / RDAP lookup
func (s *DNS) WhoisBulk(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/whois/bulk", body, params)
}

// Health DNS health audit and score
func (s *DNS) Health(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/health", params)
}

// Certificate SSL/TLS certificate inspection
func (s *DNS) Certificate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/certificate", params)
}

// Dnssec DNSSEC validation check
func (s *DNS) Dnssec(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/dnssec", params)
}

// SecurityHeaders Audit HTTP security headers
func (s *DNS) SecurityHeaders(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/security-headers", params)
}

// ZoneTransfer Test for zone transfer (AXFR) vulnerability
func (s *DNS) ZoneTransfer(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/zone-transfer", params)
}

// Typosquat Detect typosquatting domains
func (s *DNS) Typosquat(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/typosquat", params)
}

// Blacklist Check IP against 30 DNS blacklists
func (s *DNS) Blacklist(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/blacklist", params)
}

// TechStack Detect web server technology and headers
func (s *DNS) TechStack(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/tech-stack", params)
}

// Ports Scan common TCP ports
func (s *DNS) Ports(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/ports", params)
}

// Redirects Trace HTTP redirect chain
func (s *DNS) Redirects(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/redirects", params)
}

// CompanyProfile Build a company profile from a domain
func (s *DNS) CompanyProfile(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/company-profile", params)
}

// URL Decompose a URL into its component parts
func (s *DNS) URL(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/url-parse", params)
}

// HTTP Parse raw HTTP headers into structured key-value pairs
func (s *DNS) HTTP(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/http-header-parse", body, nil)
}

// Reverse Reverse DNS lookup with IP intelligence
func (s *DNS) Reverse(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/reverse", params)
}

// ASN ASN and IP intelligence lookup
func (s *DNS) ASN(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/asn", params)
}

// IP IP subnet calculator
func (s *DNS) IP(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/ip-calc", params)
}

// Generate Generate DNS records from simple inputs
func (s *DNS) Generate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/generate", params)
}

// NsPerformance Benchmark authoritative nameserver response times
func (s *DNS) NsPerformance(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/ns-performance", params)
}

// Caa Analyze CAA (Certificate Authority Authorization) records
func (s *DNS) Caa(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/caa", params)
}

// Tlsa Look up TLSA/DANE records
func (s *DNS) Tlsa(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/tlsa", params)
}

// Status Status Check
func (s *DNS) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
