// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Email provides access to the email toolkit.
type Email struct {
  client *Client
}

// NewEmail creates a new Email client.
func NewEmail(apiKey string, opts ...Option) *Email {
  return &Email{client: NewClient(apiKey, "email", opts...)}
}

// Validate2 Full email validation
func (s *Email) Validate2(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/validate", params)
}

// ValidateBatch Batch email validation
func (s *Email) ValidateBatch(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/email/validate-batch", body, nil)
}

// Catch Detect catch-all / accept-all server
func (s *Email) Catch(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/catch-all", params)
}

// Role Role vs personal account detection
func (s *Email) Role(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/role-check", params)
}

// Normalize Normalize an email address
func (s *Email) Normalize(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/normalize", params)
}

// Provider Identify email provider
func (s *Email) Provider(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/provider", params)
}

// Parse Parse raw email headers
func (s *Email) Parse(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/email/headers", body, nil)
}

// Spam Score email content for spam signals
func (s *Email) Spam(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/email/spam-score", body, nil)
}

// Gravatar Get Gravatar for an email address
func (s *Email) Gravatar(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/gravatar", params)
}

// Mailto Build or parse mailto: URIs
func (s *Email) Mailto(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/email/mailto", body, nil)
}

// Form Score a form submission for spam likelihood
func (s *Email) Form(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/email/form-spam-score", body, nil)
}

// EmailSecurity Email security posture check
func (s *Email) EmailSecurity(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/email/security", params)
}

// EmailAuth Validate email authentication (SPF, DKIM, DMARC)
func (s *Email) EmailAuth(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/email/auth", body, params)
}

// Root Root
func (s *Email) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Email) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
