// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Geo provides access to the geo toolkit.
type Geo struct {
  client *Client
}

// NewGeo creates a new Geo client.
func NewGeo(apiKey string, opts ...Option) *Geo {
  return &Geo{client: NewClient(apiKey, "geo", opts...)}
}

// IPLookup IP geolocation lookup
func (s *Geo) IPLookup(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/ip-lookup", params)
}

// IPThreat IP threat / anonymity detection
func (s *Geo) IPThreat(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/ip-threat", params)
}

// Distance Calculate distance between coordinates
func (s *Geo) Distance(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/geo/distance", body, nil)
}

// Bounding Calculate a geographic bounding box
func (s *Geo) Bounding(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/geo/bounding-box", body, nil)
}

// Center Find the geographic center of coordinates
func (s *Geo) Center(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/geo/center", body, nil)
}

// Country Get country information by ISO code
func (s *Geo) Country(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/country-info", params)
}

// Currency Get currency information by code
func (s *Geo) Currency(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/currency-info", params)
}

// TimezoneConvert Convert a timestamp between timezones
func (s *Geo) TimezoneConvert(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/timezone-convert", params)
}

// TimezoneByCoords Get timezone for coordinates
func (s *Geo) TimezoneByCoords(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/timezone-by-coords", params)
}

// TimezoneInfo Get timezone details
func (s *Geo) TimezoneInfo(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/timezone-info", params)
}

// PhoneValidate Validate and parse a phone number (E.164)
func (s *Geo) PhoneValidate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/geo/phone-validate", params)
}

// PhoneValidateBatch Batch phone number validation
func (s *Geo) PhoneValidateBatch(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/geo/phone-validate-batch", body, nil)
}

// Root Root
func (s *Geo) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Geo) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
