// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Image provides access to the image toolkit.
type Image struct {
  client *Client
}

// NewImage creates a new Image client.
func NewImage(apiKey string, opts ...Option) *Image {
  return &Image{client: NewClient(apiKey, "image", opts...)}
}

// ImageResize Resize an image
func (s *Image) ImageResize(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/resize", params)
}

// ImageCrop Crop an image
func (s *Image) ImageCrop(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/crop", params)
}

// ImageRotate Rotate an image
func (s *Image) ImageRotate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/rotate", params)
}

// ImageFlip Flip an image
func (s *Image) ImageFlip(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/flip", params)
}

// ImageCompress Compress an image
func (s *Image) ImageCompress(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/compress", params)
}

// ImageStripExif Strip EXIF metadata
func (s *Image) ImageStripExif(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/strip-exif", params)
}

// ImageTrim Auto-trim image borders
func (s *Image) ImageTrim(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/trim", params)
}

// ImagePad Add padding to an image
func (s *Image) ImagePad(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/pad", params)
}

// ImageComposite Composite two images
func (s *Image) ImageComposite(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/composite", params)
}

// ImageDither Reduce to a limited colour palette
func (s *Image) ImageDither(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/dither", params)
}

// ImageRemoveBackground Remove image background
func (s *Image) ImageRemoveBackground(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/remove-background", params)
}

// ImageFilterGrayscale Convert to grayscale
func (s *Image) ImageFilterGrayscale(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/filter/grayscale", params)
}

// ImageFilterBlur Apply Gaussian blur
func (s *Image) ImageFilterBlur(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/filter/blur", params)
}

// ImageFilterSharpen Sharpen an image
func (s *Image) ImageFilterSharpen(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/filter/sharpen", params)
}

// ImageFilterSepia Apply sepia tone
func (s *Image) ImageFilterSepia(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/filter/sepia", params)
}

// ImageAdjustBrightness Adjust brightness
func (s *Image) ImageAdjustBrightness(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/adjust/brightness", params)
}

// ImageAdjustContrast Adjust contrast
func (s *Image) ImageAdjustContrast(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/adjust/contrast", params)
}

// ImageAdjustSaturation Adjust saturation
func (s *Image) ImageAdjustSaturation(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/adjust/saturation", params)
}

// ImagePlaceholderPlaceholder Generate a placeholder image
func (s *Image) ImagePlaceholderPlaceholder(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/image/placeholder", body, nil)
}

// ImagePlaceholderPlaceholder1 Generate a placeholder image (raw)
func (s *Image) ImagePlaceholderPlaceholder1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/placeholder", params)
}

// ImageWatermarkText Add a text watermark
func (s *Image) ImageWatermarkText(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/watermark/text", params)
}

// ImageWatermarkImage Add an image watermark
func (s *Image) ImageWatermarkImage(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/watermark/image", params)
}

// ImageExtractMetadataMetadata Extract image metadata (EXIF)
func (s *Image) ImageExtractMetadataMetadata(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/image/extract/metadata", body, nil)
}

// ImageExtractMetadataMetadata1 Extract image metadata from URL
func (s *Image) ImageExtractMetadataMetadata1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/extract/metadata", params)
}

// ImageExtractColorsColors Extract dominant colour palette
func (s *Image) ImageExtractColorsColors(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/image/extract/colors", body, nil)
}

// ImageExtractColorsColors1 Extract colour palette from URL
func (s *Image) ImageExtractColorsColors1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/extract/colors", params)
}

// ImageFavicon Fetch highest-resolution favicon
func (s *Image) ImageFavicon(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/favicon", params)
}

// Download Download a processed image
func (s *Image) Download(ctx context.Context, objectName string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/image/download/%s", objectName), nil)
}

// ImageFromHTML Render raw HTML/CSS as an image
func (s *Image) ImageFromHTML(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/image/from-html", body, nil)
}

// ImageFromTemplate Render a Liquid template as an image
func (s *Image) ImageFromTemplate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/image/from-template", body, nil)
}

// List List pre-built image templates
func (s *Image) List(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/templates", params)
}

// Get Get a single image template
func (s *Image) Get(ctx context.Context, templateId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/image/templates/%s", templateId), nil)
}

// Convert2 Convert between image formats
func (s *Image) Convert2(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/image/convert", body, nil)
}

// Convert21 Convert image via URL (file download)
func (s *Image) Convert21(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/image/convert", params)
}

// Root Root
func (s *Image) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Image) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
