// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Media provides access to the media toolkit.
type Media struct {
  client *Client
}

// NewMedia creates a new Media client.
func NewMedia(apiKey string, opts ...Option) *Media {
  return &Media{client: NewClient(apiKey, "media", opts...)}
}

// YoutubeTranscript Get YouTube video transcript
func (s *Media) YoutubeTranscript(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/transcript", params)
}

// YoutubeBatch Batch transcript extraction
func (s *Media) YoutubeBatch(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/youtube/transcript/batch", body, nil)
}

// YoutubeBatch1 Get batch transcript job status
func (s *Media) YoutubeBatch1(ctx context.Context, jobId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/youtube/transcript/batch/%s", jobId), nil)
}

// YoutubeVideo Get YouTube video metadata
func (s *Media) YoutubeVideo(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/video", params)
}

// YoutubeChannel Get YouTube channel info
func (s *Media) YoutubeChannel(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/channel", params)
}

// YoutubeVideos List channel video IDs
func (s *Media) YoutubeVideos(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/channel/videos", params)
}

// YoutubePlaylist Get playlist info
func (s *Media) YoutubePlaylist(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/playlist", params)
}

// YoutubeVideos1 List playlist video IDs
func (s *Media) YoutubeVideos1(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/playlist/videos", params)
}

// YoutubeSearch Search YouTube
func (s *Media) YoutubeSearch(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/youtube/search", params)
}

// Root Root
func (s *Media) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Media) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
