// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Pdf provides access to the pdf toolkit.
type Pdf struct {
  client *Client
}

// NewPdf creates a new Pdf client.
func NewPdf(apiKey string, opts ...Option) *Pdf {
  return &Pdf{client: NewClient(apiKey, "pdf", opts...)}
}

// Merge Merge multiple PDFs into one
func (s *Pdf) Merge(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/pdf/merge", body, nil)
}

// Split Split a PDF into parts
func (s *Pdf) Split(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/split", params)
}

// Rotate Rotate PDF pages
func (s *Pdf) Rotate(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/rotate", params)
}

// Compress Compress a PDF to reduce file size
func (s *Pdf) Compress(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/compress", params)
}

// Watermark Add a text watermark to PDF pages
func (s *Pdf) Watermark(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/watermark", params)
}

// Protect Encrypt or decrypt a PDF
func (s *Pdf) Protect(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/pdf/protect", body, nil)
}

// FromImages Combine images into a PDF
func (s *Pdf) FromImages(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/pdf/from-images", body, nil)
}

// Text Extract text from a PDF
func (s *Pdf) Text(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/text", params)
}

// Metadata Read or update PDF metadata
func (s *Pdf) Metadata(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/pdf/metadata", body, nil)
}

// Table Extract tables from a PDF
func (s *Pdf) Table(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/table-extract", params)
}

// Form Read or fill PDF form fields
func (s *Pdf) Form(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/pdf/form-fields", body, nil)
}

// Info Get structural information about a PDF
func (s *Pdf) Info(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/info", params)
}

// Ocr Extract text from scanned/image PDFs using OCR
func (s *Pdf) Ocr(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/ocr", params)
}

// FromTemplate Generate PDF from a Liquid template
func (s *Pdf) FromTemplate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/pdf/from-template", body, nil)
}

// To Render PDF pages as images
func (s *Pdf) To(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/to-images", params)
}

// Convert Convert document via URL (file download)
func (s *Pdf) Convert(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/convert/document", params)
}

// Download Download a processed file
func (s *Pdf) Download(ctx context.Context, objectName string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/pdf/download/%s", objectName), nil)
}

// List List pre-built PDF templates
func (s *Pdf) List(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/pdf/templates", params)
}

// Get Get a single PDF template
func (s *Pdf) Get(ctx context.Context, templateId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/pdf/templates/%s", templateId), nil)
}

// Root Root
func (s *Pdf) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Pdf) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
