// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Scrape provides access to the scrape toolkit.
type Scrape struct {
  client *Client
}

// NewScrape creates a new Scrape client.
func NewScrape(apiKey string, opts ...Option) *Scrape {
  return &Scrape{client: NewClient(apiKey, "scrape", opts...)}
}

// SeoAudit Full page SEO audit
func (s *Scrape) SeoAudit(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/audit", params)
}

// SeoKeywordDensity Keyword density and readability analysis
func (s *Scrape) SeoKeywordDensity(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/keyword-density", params)
}

// SeoMobileFriendly Mobile-friendliness check
func (s *Scrape) SeoMobileFriendly(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/mobile-friendly", params)
}

// SeoBrokenLinks Broken link checker
func (s *Scrape) SeoBrokenLinks(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/broken-links", params)
}

// SeoPagespeed Page speed metrics
func (s *Scrape) SeoPagespeed(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/pagespeed", params)
}

// SeoBulkAudit Bulk SEO audit for multiple URLs
func (s *Scrape) SeoBulkAudit(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/scrape/bulk-audit", body, nil)
}

// SeoCompare Side-by-side SEO comparison
func (s *Scrape) SeoCompare(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/scrape/compare", body, nil)
}

// Scrape Unified Scrape
func (s *Scrape) Scrape(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/scrape", body, nil)
}

// Pdf Extract PDF Text
func (s *Scrape) Pdf(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/scrape/pdf", body, nil)
}

// ParseSitemap Parse Sitemap
func (s *Scrape) ParseSitemap(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/sitemap", params)
}

// ParseRobots Parse robots.txt
func (s *Scrape) ParseRobots(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/robots", params)
}

// Map Discover URLs on a Domain
func (s *Scrape) Map(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/scrape/map", params)
}

// Start Start Multi-Page Crawl
func (s *Scrape) Start(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/scrape/crawl", body, nil)
}

// Get Get Crawl Job Status
func (s *Scrape) Get(ctx context.Context, jobId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/scrape/crawl/%s", jobId), nil)
}

// Screenshot2 Capture webpage screenshot
func (s *Scrape) Screenshot2(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/screenshot", body, params)
}

// ScreenshotPdf Capture webpage as PDF
func (s *Scrape) ScreenshotPdf(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/screenshot/pdf", body, params)
}

// ScreenshotElement Capture specific page element
func (s *Scrape) ScreenshotElement(ctx context.Context, params map[string]string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/screenshot/element", body, params)
}

// Download Download a screenshot
func (s *Scrape) Download(ctx context.Context, objectName string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/screenshot/download/%s", objectName), nil)
}

// Fetch Fetch (GET shortcut)
func (s *Scrape) Fetch(ctx context.Context, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, "v1/fetch", params)
}

// Root Root
func (s *Scrape) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Scrape) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
