// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
)

// Textanalysis provides access to the textanalysis toolkit.
type Textanalysis struct {
  client *Client
}

// NewTextanalysis creates a new Textanalysis client.
func NewTextanalysis(apiKey string, opts ...Option) *Textanalysis {
  return &Textanalysis{client: NewClient(apiKey, "textanalysis", opts...)}
}

// Readability Readability Score
func (s *Textanalysis) Readability(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/readability", body, nil)
}

// Summarize Summarize
func (s *Textanalysis) Summarize(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/summarize", body, nil)
}

// TextSimilarity Text Similarity
func (s *Textanalysis) TextSimilarity(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/similarity", body, nil)
}

// TextDiff Text Diff
func (s *Textanalysis) TextDiff(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/diff", body, nil)
}

// Data Data Mask
func (s *Textanalysis) Data(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/mask", body, nil)
}

// Profanity Profanity Filter
func (s *Textanalysis) Profanity(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/profanity", body, nil)
}

// Word Word Frequency
func (s *Textanalysis) Word(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/word-frequency", body, nil)
}

// Detect Detect Language
func (s *Textanalysis) Detect(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/detect-language", body, nil)
}

// Transliterate Transliterate Text
func (s *Textanalysis) Transliterate(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/text/transliterate", body, nil)
}

// Root Root
func (s *Textanalysis) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Textanalysis) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
