// Code generated by generate_go_sdk.ts. DO NOT EDIT.
package toolkitapi

import (
  "context"
  "fmt"
)

// Webhook provides access to the webhook toolkit.
type Webhook struct {
  client *Client
}

// NewWebhook creates a new Webhook client.
func NewWebhook(apiKey string, opts ...Option) *Webhook {
  return &Webhook{client: NewClient(apiKey, "webhook", opts...)}
}

// CreateBins Create a request bin
func (s *Webhook) CreateBins(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/bins", body, nil)
}

// GetBins Get bin details
func (s *Webhook) GetBins(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/bins/%s", binId), nil)
}

// DeleteBins Delete a bin
func (s *Webhook) DeleteBins(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Delete(ctx, fmt.Sprintf("v1/bins/%s", binId), nil)
}

// List List captured requests
func (s *Webhook) List(ctx context.Context, binId string, params map[string]string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/bins/%s/requests", binId), params)
}

// GetRequests Get captured request detail
func (s *Webhook) GetRequests(ctx context.Context, binId string, requestId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/bins/%s/requests/%s", binId, requestId), nil)
}

// Replay Replay a captured request
func (s *Webhook) Replay(ctx context.Context, binId string, requestId string, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, fmt.Sprintf("v1/bins/%s/requests/%s/replay", binId, requestId), body, nil)
}

// Catch2 Catch and record an HTTP request
func (s *Webhook) Catch2(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/catch/%s", binId), nil)
}

// Catch21 Catch and record an HTTP request
func (s *Webhook) Catch21(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Options(ctx, fmt.Sprintf("v1/catch/%s", binId), nil, nil)
}

// Catch22 Catch and record an HTTP request
func (s *Webhook) Catch22(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Head(ctx, fmt.Sprintf("v1/catch/%s", binId), nil, nil)
}

// Catch23 Catch and record an HTTP request
func (s *Webhook) Catch23(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Post(ctx, fmt.Sprintf("v1/catch/%s", binId), nil, nil)
}

// Catch24 Catch and record an HTTP request
func (s *Webhook) Catch24(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Delete(ctx, fmt.Sprintf("v1/catch/%s", binId), nil)
}

// Catch25 Catch and record an HTTP request
func (s *Webhook) Catch25(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Patch(ctx, fmt.Sprintf("v1/catch/%s", binId), nil, nil)
}

// Catch26 Catch and record an HTTP request
func (s *Webhook) Catch26(ctx context.Context, binId string) (interface{}, error) {
  return s.client.Put(ctx, fmt.Sprintf("v1/catch/%s", binId), nil, nil)
}

// CreateMocks Create a mock endpoint
func (s *Webhook) CreateMocks(ctx context.Context, body interface{}) (interface{}, error) {
  return s.client.Post(ctx, "v1/mocks", body, nil)
}

// GetMocks Get mock endpoint details
func (s *Webhook) GetMocks(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/mocks/%s", mockId), nil)
}

// DeleteMocks Delete a mock endpoint
func (s *Webhook) DeleteMocks(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Delete(ctx, fmt.Sprintf("v1/mocks/%s", mockId), nil)
}

// HitMock Hit a mock endpoint
func (s *Webhook) HitMock(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Get(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil)
}

// HitMock1 Hit a mock endpoint
func (s *Webhook) HitMock1(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Options(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil, nil)
}

// HitMock2 Hit a mock endpoint
func (s *Webhook) HitMock2(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Head(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil, nil)
}

// HitMock3 Hit a mock endpoint
func (s *Webhook) HitMock3(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Post(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil, nil)
}

// HitMock4 Hit a mock endpoint
func (s *Webhook) HitMock4(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Delete(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil)
}

// HitMock5 Hit a mock endpoint
func (s *Webhook) HitMock5(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Patch(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil, nil)
}

// HitMock6 Hit a mock endpoint
func (s *Webhook) HitMock6(ctx context.Context, mockId string) (interface{}, error) {
  return s.client.Put(ctx, fmt.Sprintf("v1/mock/%s", mockId), nil, nil)
}

// Root Root
func (s *Webhook) Root(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "", nil)
}

// Status Status
func (s *Webhook) Status(ctx context.Context) (interface{}, error) {
  return s.client.Get(ctx, "v1/status", nil)
}
